
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/LocalLoanApp
    username: #####
    password: #####
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

    # Server configuration
server:
  port: 9090 #set your port

logging:
  level:
    org.usra.loanService: DEBUG


#logging:
#  level:
#    org.hibernate: DEBUG
#    org.hibernate.SQL: DEBUG

#spring:
#  config:
#    activate:
#      on-profile: test
#name: LoanService
#environment: testing
#enabled: false
#servers:
#  - www.abc.test.com
#  - www.xyz.test.com
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#name: prod-YAML
#environment: production
#enabled: true
#servers:
#  - www.abc.com
#  - www.xyz.com

